### ISSUE TITLE
Error when running extract_helix_one

### ISSUE THREAD

**Issue by ShuhaoGithub** [LPDI-EPFL/masif_seed#1]
Hi, I ran into this error when running the first step of masif_seed. May I ask how to solve this? Thanks!

root@df6a6de34df2:/masif/design/masif_seed/masif/data/masif_peptides# ./data_extract_helix_one.sh 4QVF_B
Downloading PDB structure '4QVF'...
Protonating file /var/tmp/4QVF.pdb
Traceback (most recent call last):
  File "/masif/design/masif_seed/masif/source/data_preparation/01b-helix_extract_and_triangulate.py", line 75, in <module>
    helices = computeHelices(pdb_id, pdb_filename, chain_id)
  File "/masif/design/masif_seed/masif/source/data_preparation/01b-helix_extract_and_triangulate.py", line 33, in computeHelices
    dssp = DSSP(model, pdbfilename)
  File "/usr/local/lib/python3.6/site-packages/Bio/PDB/DSSP.py", line 438, in __init__
    dssp_dict, dssp_keys = dssp_dict_from_pdb_file(in_file, dssp)
  File "/usr/local/lib/python3.6/site-packages/Bio/PDB/DSSP.py", line 236, in dssp_dict_from_pdb_file
    stderr=subprocess.PIPE,
  File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'mkdssp': 'mkdssp'

**Comment by bud-graziano** [comment]
Hi Shuhao, unfortunately I wasn't able to reproduce the error...

Just to double-check, you're running MaSIF within the docker container, correct?

Could you please provide the output of `apt list --installed` and `pip3 list`?
