### ISSUE TITLE
Missing file: `models/weights_12A_0129.hdf5`

### ISSUE THREAD

**Issue by mokurin000** [LPDI-EPFL/masif_seed#23]
I had most steps runs without any issue (with manual fix of soft links), but in the last step, It's tring to load `models/weights_12A_0129.hdf5`, which does not exists in `scoring_nn`. Aliasing `weights_seed_benchmark_12A_0123.hdf5` does not work too, it says:
```text
Traceback (most recent call last):
  File "/home/yuxuan/桌面/masif_seed-main/masif_seed_search/source/masif_seed_search_nn.py", line 43, in <module>
    nn_score_atomic.restore_model()
  File "/home/yuxuan/桌面/masif_seed-main/masif_seed_search/source/alignment_evaluation_nn.py", line 122, in restore_model
    self.model.load_weights(self.model_name)
  File "/home/yuxuan/micromamba/envs/masif/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 183, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/home/yuxuan/micromamba/envs/masif/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 1374, in load_weights
    saving.load_weights_from_hdf5_group(f, self.layers)
  File "/home/yuxuan/micromamba/envs/masif/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 671, in load_weights_from_hdf5_group
    ' layers.')
ValueError: You are trying to load a weight file containing 17 layers into a model with 0 layers.

```

**Comment by mokurin000** [comment]
```yaml
# micromamba create --file=./env.yaml
name: masif
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - mx
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_4
  - backports.functools_lru_cache=2.0.0=pyhd8ed1ab_0
  - biopython=1.79=py36h8f6f2f9_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.8.30=hbcca054_0
  - cmake=3.22.1=h1fce559_0
  - colour=0.1.5=py_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - expat=2.6.3=h6a678d5_0
  - ipython=7.16.1=py36he448a4c_2
  - ipython_genutils=0.2.0=pyhd8ed1ab_1
  - jedi=0.17.2=py36h5fab9bb_1
  - krb5=1.20.1=h568e23c_1
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libblas=3.9.0=20_linux64_openblas
  - libcblas=3.9.0=20_linux64_openblas
  - libcurl=8.2.1=h91b91d3_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - liblapack=3.9.0=20_linux64_openblas
  - libnghttp2=1.52.0=ha637b67_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuv=1.48.0=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - msms=2.6.1=h516909a_0
  - ncurses=6.5=he02047a_1
  - numpy=1.19.5=py36hfc0c790_2
  - openssl=1.1.1w=hd590300_0
  - parso=0.7.1=pyh9f0ad1d_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=21.3.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pymesh2=0.3=py36h9f0ad1d_0
  - python=3.6.15=hb7a2778_0_cpython
  - python_abi=3.6=2_cp36m
  - readline=8.2=h8228510_1
  - reduce=3.24=0
  - rhash=1.4.1=h3c74f83_1
  - scipy=1.5.3=py36h81d768a_1
  - setuptools=58.0.4=py36h5fab9bb_2
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - traitlets=4.3.3=pyhd8ed1ab_2
  - wcwidth=0.2.10=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - tk=8.6.13=noxft_h4845f30_101
  - zlib
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.4.0
    - addict==2.4.0
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astor==0.8.1
    - async-generator==1.10
    - attrs==22.2.0
    - Babel==2.11.0
    - bleach==4.1.0
    - certifi==2024.8.30
    - cffi==1.15.1
    - charset-normalizer==2.0.12
    - colour==0.1.5
    - comm==0.1.4
    - contextvars==2.4
    - cycler==0.11.0
    - dask==1.2.2
    - dataclasses==0.8
    - decorator==4.4.2
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - entrypoints==0.4
    - gast==0.2.2
    - google-pasta==0.2.0
    - grpcio==1.48.2
    - h5py==2.10.0
    - idna==3.10
    - immutables==0.19
    - importlib-metadata==4.8.3
    - importlib-resources==5.4.0
    - ipykernel==5.5.6
    - ipywidgets==7.8.5
    - Jinja2==3.0.3
    - joblib==1.1.1
    - json5==0.9.16
    - jsonschema==3.2.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.2
    - jupyter-packaging==0.10.6
    - jupyter-server==1.13.1
    - jupyterlab==3.2.9
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.10.3
    - jupyterlab_widgets==1.1.11
    - Keras-Applications==1.0.8
    - Keras-Preprocessing==1.1.2
    - kiwisolver==1.3.1
    - Markdown==3.3.7
    - MarkupSafe==2.0.1
    - matplotlib==3.3.4
    - mistune==0.8.4
    - nbclassic==0.3.5
    - nbclient==0.5.9
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.6.0
    - networkx==2.5.1
    - notebook==6.4.10
    - numpy==1.18.5
    - open3d==0.8.0.0
    - opt-einsum==3.3.0
    - packaging==21.3
    - pandas==1.1.5
    - pandocfilters==1.5.1
    - Pillow==8.4.0
    - prometheus-client==0.17.1
    - protobuf==3.19.6
    - pycparser==2.21
    - pyparsing==3.1.4
    - pyquaternion==0.9.9
    - pyrsistent==0.18.0
    - python-dateutil==2.9.0.post0
    - python-version==0.0.2
    - pytz==2024.2
    - PyYAML==6.0.1
    - pyzmq==25.1.2
    - requests==2.27.1
    - scikit-learn==0.24.2
    - Send2Trash==1.8.3
    - sniffio==1.2.0
    - tensorboard==1.12.2
    - tensorflow==1.12.0
    - tensorflow-estimator==1.15.1
    - termcolor==1.1.0
    - terminado==0.12.1
    - testpath==0.6.0
    - threadpoolctl==3.1.0
    - tomlkit==0.11.6
    - tornado==6.1
    - tqdm==4.64.1
    - typing_extensions==4.1.1
    - urllib3==1.26.20
    - webencodings==0.5.1
    - websocket-client==1.3.1
    - Werkzeug==2.0.3
    - widgetsnbextension==3.6.10
    - wrapt==1.16.0
    - zipp==3.6.0
```

Switching to tensorflow 1.12 resolved the issue.
